### PR TITLE
Add autoTransport options for self-initialization

### PR DESCRIPTION
**Pull request by 19h**
Add a autoTransport option to let gossipmonger initialize a gossipmonger-tcp-transport conform transport with the given transport information automatically.

This is in frame with my gossipmonger-zmq-transport, so that the user can simply write:
`transport: require("gossipmonger-zmq-transport")`

### CODE REVIEW

**Comment by tristanls** [comment]
This should be done before initializing Gossipmonger and then sort of dependency injected.

So, I would say something like:

``` javascript
var Gossipmonger = require('gossipmonger');
var Transport = require('gossipmonger-zmq-transport');
var transport = new Transport(/*your init options here*/);

transport.listen(); // or transport.start(), anything to make it start listening...

/* once it's set up and ready to go, pass it to gossipmonger */

var gossipmonger = new Gossipmonger(
    {/* peerInfo */}, 
    { transport : transport, seeds: [ /* seeds */ ]}
);
```

**Comment by 19h** [comment]
_to let gossipmonger initialize a gossipmonger-tcp-transport conform transport_ — this is plain sugar for initializing transports that do not require special arguments.

**Comment by 19h** [comment]
For instance:

```
    var gossipmonger = new Gossipmonger({
            id: "test",
            transport: {
                    host: "2.2.2.2",
                    port: 9876
            }
    }, {
            seeds: [{...}],
            transport: require("gossipmonger-zmq-transport"),
            autoTransport: true
    });
```

**Comment by tristanls** [comment]
I think it would be a mistake to add this functionality. I am not going to add it. Below is my reasoning:

The benefits are:
- passing an uninitialized constructor function to Gossipmonger as a transport
- not having to call `new` on the transport

The costs are:
- adding `options.autoTransport` option
- setting a precedent for `options.transport` not being consistent (in certain cases it is ready to go and an already running server, in other cases it is an initialized but not running object, and in other cases it is a constructor function itself)
- Gossipmonger having to call `new` on the transport and now taking on additional responsibility of initializing independent modules

Based on the above, we would be sacrificing simplicity of implementation for a convenience that is of questionable value to me. Furthermore, the user of the module knows everything about the `transport` that is being given to Gossipmonger. It is not the responsibility of Gossipmonger to start the `transport`. Perhaps this is poor naming on my part. Gossipmonger is not really useful by itself, but it is meant to be a component of an application. I think of it more as `gossipmonger-core`. This means that some application will create a `transport`, create `storage` and create `core` and then hook them together.

**Comment by 19h** [comment]
Indeed, convinced me. Closing this. After all we could document this as `gossipmonger-core` being as a component attachable to a transport? I understand your assumption that `transport`, `storage` and `core` should be assembled manually; I'd like to provide a convenience package, though, that makes all of this more accessible to people who just want to get some nodes talk to each other :)

**Comment by tristanls** [comment]
I'm for convenience packages. You're right, that would help to hack around with, experimenting, and not having to write a script and hook things together every time. :)

**Pull request closed without merging**
